### ISSUE TITLE
sample rate of 3-axis accelerator

### ISSUE THREAD

**Issue by cjh8817676** [HimaxWiseEyePlus/bsp_tflu#3]
How could I adjust the sample rate of accelerator on HIMAX-WE1 .

**Comment by bigcat-himax** [comment]
Hi, 
    We are planning to upgrade SDK library and will take this into consideration. 
Thanks.

**Comment by bigcat-himax** [comment]
Hi, cjh8817676:
    Please check the example here for direct control to accelerator by I2C
https://github.com/HimaxWiseEyePlus/WE_I_Plus_User_Examples/blob/main/direct_i2c_accelerometer/examples/magic_wand/imu_lsm9ds1.c
   accelerator datasheet link:
https://www.st.com/resource/en/datasheet/lsm9ds1.pdf
   SDK now update to v20 which support I2C control to accelerator

Thanks.
