### ISSUE TITLE
not showing anything on console after selecting the image for the transfer in Mac

### ISSUE THREAD

**Issue by chinya07** [HimaxWiseEyePlus/bsp_tflu#4]
Following the instruction upto step 8, when I am selecting the .img file for flashing there is a black blank screen with no transfer status. Attaching the screenshot of the same

<img width="1792" alt="Screenshot 2022-08-05 at 3 53 36 PM" src="https://user-images.githubusercontent.com/38719024/183104745-e3c9dc0c-b7b7-4036-af7b-aeff3e04b4b2.png">

.

**Comment by kris-himax** [comment]
@chinya07 , hi
Did you do the step 5 and step 6 to let WE-I to enter receiving mode?
![image](https://user-images.githubusercontent.com/87454575/184092868-834fbcea-05a8-4ab3-8f5e-fe1de6bfa6c7.png)

**Comment by chinya07** [comment]
Hi @kris-himax, sorry for replying so late, yes I followed the same steps as given in the documentation but for some reason I couldn't see anything on the console for this step. Anyway I ignored this issue by installing a Ubuntu VM on mac and it worked but not sure if we should close this or not.
