### ISSUE TITLE
workshop_example - LAB3_microphone

### ISSUE THREAD

**Issue by kevin789654tw** [HimaxWiseEyePlus/bsp_tflu#5]
Dear @kris-himax

Hi, Kris. It's me again. I've burn LAB3_microphone.img into "Himax WE-I Plus".
But I'm wondering the meaning about channel data.
Is it the left and right channel data a bit like amplitude value? 
Or LAB3_microphone.img is just collect sound data? 
Thanks for your help!!!

Best Regards,
Kevin

**Comment by kris-himax** [comment]
@kevin789654tw , hi

The left and right channel data are a bit like amplitude values which range is from -32,768 to 32,767. 
You can also normalize them to -1 to 1 depend on your use case.

Thanks,
Kris

**Comment by kevin789654tw** [comment]
Dear @kris-himax

Thank you, Kris. 
I'm also a little confuse about the flow of example. 

My thought about flow:
1. "Wait for user press key: [R]"
2. Press [R], then "Start Record Audio"
3. Record sound for 3 sec...
4. After 3 sec, then print "Microphone Get Data Success" & "Start to send"
5. Print 3 sec data (3sec*16KHz = 48,000 data point)
6. Print "End of send"

If I am wrong, please correct me. Thank you~
I'm curious if the data is being stored, is it being stored in SRAM?
Thanks for helping again!!!


Best Regards,
Kevin

**Comment by kris-himax** [comment]
@kevin789654tw ,hi

I do the memcpy to store at audio_clip array.
And it is at SRAM.

Thanks,
Kris

**Comment by kevin789654tw** [comment]
Dear @kris-himax

Thank you, Kris. Thanks for your help!!!

Best Regards,
Kevin
